eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8020
spring:
  application:
    name: zuul
zuul:
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
#  sensitive-headers:
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: spring-cloud-test1

ribbon:
  ReadTimeout: 9000
  ConnectTimeout: 6000